config/routes.rb
Codedoor::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'application#main'

  resources :programmers, only: [:index, :show]

  resources :jobs, only: [:index, :new, :create, :edit] do
    get :new_application, on: :new
    post :create_application, on: :new

    post :create_message, on: :member
    post :cancel, on: :member
    post :offer, on: :member
    post :decline, on: :member
    post :start, on: :member
    post :finish, on: :member
  end

  resources :job_listings, only: [:index, :show, :new, :edit, :create, :update]

  resources :users, only: [:edit, :update] do
    resource :programmer, only: [:edit, :update] do
      post :verify_contribution, defaults: { format: :json }
    end
    resource :client, only: [:new, :create, :edit, :update]
    # resource :payment_info, only: [:edit] do
    #   # The Balanced Payments API scrubs the _method parameter, so :update must be a POST
    #   post :update, defaults: { format: :json }
    # end
  end

  resources :blog, only: [:index, :show]

  get '/terms', to: 'legal#terms'
  get '/sitemap.xml.gz', to: 'sitemaps#show'
  get '/login', to: 'login#main'

end

app/models/job.rb
class Job < ActiveRecord::Base
  include HasRate

  belongs_to :client
  belongs_to :programmer
  has_many :job_messages, dependent: :destroy
  accepts_nested_attributes_for :job_messages

  validates :client_id, presence: true
  validates :programmer_id, presence: true
  validates :name, presence: true
  validates :availability, inclusion: { in: ['part-time', 'full-time'], message: 'must be selected' }
  validates :started_at, presence: true, if: Proc.new{|p| p.running? || p.finished?}
  validates :finished_at, presence: true, if: Proc.new{|p| p.finished? || p.disabled?}

  validate :client_and_programmer_are_different
  validate :rate_is_unchanged, unless: :has_not_or_has_just_started?
  validate :availability_is_unchanged, unless: :has_not_or_has_just_started?
  validate :finished_after_started, if: Proc.new{|p| p.started_at && p.finished_at}

  before_validation :normalize_by_rate_type

  after_save :calculate_programmer_availability

  state_machine :state, initial: :has_not_started do
    before_transition to: :running do |job, transition|
      job.started_at = Time.now
    end

    before_transition to: [:finished, :disabled] do |job, transition|
      job.finished_at = Time.now
    end

    event :offer do
      transition has_not_started: :offered
    end

    event :cancel do
      transition offered: :canceled
    end

    event :decline do
      transition offered: :declined
    end

    event :start do
      transition offered: :running
    end

    event :finish do
      transition running: :finished
    end

    event :disable do
      transition all => :disabled
    end
  end

  def is_client?(user)
    raise 'Called is_client? for non-user' unless user.kind_of?(User)
    client.user == user
  end

  def other_user(user)
    raise 'Called other_user for non-user' unless user.kind_of?(User)
    (client.user == user) ? programmer.user : client.user
  end

  def hourly?
    rate_type == 'hourly'
  end

  def fixed_price?
    rate_type == 'fixed_price'
  end

  private

  def normalize_by_rate_type
    if fixed_price?
      self.hourly_rate = nil
    elsif hourly?
      self.fixed_rate = nil
    end
  end

  def calculate_programmer_availability
    if finished? || disabled? || running?
      self.programmer.calculate_calculated_availability
      self.programmer.save!
    end
  end

  def client_and_programmer_are_different
    # NOTE: This would only throw an exception if the client or programmer are missing, but that's invalid
    begin
      errors.add(:programmer, 'must refer to a different user') if client.user == programmer.user
    rescue
    end
  end

  def has_not_or_has_just_started?
    state_was.nil? || state_was == 'has_not_started'
  end

  # TODO: If negotiation is allowed, then this would change
  def rate_is_unchanged
    errors.add(:hourly_rate, 'must stay the same for the job') if hourly_rate_changed?
  end

  def availability_is_unchanged
    errors.add(:availability, 'must stay the same for the job') if availability_changed?
  end

  def finished_after_started
    errors.add(:finished_at, 'must come after time started at') if finished_at < started_at
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :client_or_programmer_required, only: [:index, :edit, :create_message, :finish]
  before_filter :client_required, only: [:new, :create]
  before_filter :programmer_required, only: [:new_application, :create_application]

  before_filter :required_account_is_conditional, only: [:offer, :cancel, :start, :decline]

  load_and_authorize_resource except: [:create, :create_message, :offer, :start, :cancel, :decline, :finish, :new_application, :create_application]

  def index
    if current_user.client.present?
      @jobs_as_client = Job.where(client_id: current_user.client.id)
      @job_listings_as_client = JobListing.where(client_id: current_user.client.id)
    else
      @jobs_as_client = []
      @job_listings_as_client = []
    end
    @jobs_as_programmer = current_user.completed_programmer_account? ? Job.where(programmer_id: current_user.programmer.id) : []
  end

  def new
    @programmer = Programmer.find(params[:programmer_id])

    redirect_cannot_be_found if @programmer.unavailable?
    redirect_to_existing_job(@programmer, current_user.client)

    # NOTE: It should be JobFromDirectContact, but that would muck up the hidden parameters to be saved
    @job = Job.new(client_id: current_user.client.id, programmer_id: @programmer.id, hourly_rate: @programmer.hourly_rate, availability: @programmer.availability, rate_type: 'hourly')
  end

  def create
    @job = JobFromDirectContact.new(create_job_params)
    @programmer = @job.programmer
    redirect_cannot_be_found if @programmer.unavailable?

    @job.client_id = current_user.client.id
    @job.hourly_rate = @programmer.hourly_rate
    @job.rate_type = 'hourly'
    @job.availability = @programmer.availability
    @job.job_messages.first.sender_is_client = true if @job.job_messages.present?

    authorize! :create, @job
    create_job_or_message(offer_job_with_message(@job), @job.job_messages.first, :new)
  end

  def new_application
    @job_listing = JobListing.find(params[:job_listing_id])

    @programmer = current_user.programmer

    redirect_to_existing_job(@programmer, @job_listing.client)

    authorize! :read, @job_listing

    # NOTE: Only use JobFromApplication for additional validation rules on create
    @job = Job.new(client_id: @job_listing.client_id, programmer_id: @programmer.id, job_listing_id: @job_listing.id)

    @job.rate_type = @job_listing.suggested_rate_type
  end

  def create_application
    @job = JobFromApplication.new(create_job_application_params)
    @programmer = current_user.programmer
    @job_listing = JobListing.find(@job.job_listing_id)
    redirect_cannot_be_found if @programmer.unavailable?

    @job.programmer = @programmer
    @job.client = @job_listing.client
    @job.name = @job_listing.title
    @job.availability = @programmer.unavailable? ? 'part-time' : @programmer.availability

    authorize! :create, @job
    create_job_or_message(offer_job_with_message(@job), @job.job_messages.first, :new_application)
  end

  def edit
    @programmer = @job.programmer
  end

  def create_message
    @job = Job.find(params[:id])
    authorize! :update, @job
    @programmer = @job.programmer
    @job_message = JobMessage.new(create_message_params)
    @job_message.sender_is_client = @job.is_client?(current_user)
    @job.job_messages << @job_message

    create_job_or_message(offer_job_with_message(@job), @job_message, :edit)
  end

  def offer
    # The rate and availability gets locked at the time of offer
    state_change({direct_contact: :update_as_client, application: :update_as_programmer}, ->{@job.has_not_started?}, ->{@job.availability = @job.programmer.availability; @job.hourly_rate = @job.programmer.hourly_rate; @job.offer!}, :offered, 'The job has been offered.', 'The job could not be offered.')
  end

  def cancel
    state_change({direct_contact: :update_as_client, application: :update_as_programmer}, job_offered_lambda, ->{@job.cancel!}, :canceled, 'The job has been canceled.', 'The job could not be canceled.')
  end

  def start
    state_change({direct_contact: :update_as_programmer, application: :update_as_client}, job_offered_lambda, ->{@job.start!}, :started, 'The job has been started.', 'The job could not be started.')
  end

  def decline
    state_change({direct_contact: :update_as_programmer, application: :update_as_client}, job_offered_lambda, ->{@job.decline!}, :declined, 'The job has been declined.', 'The job could not be declined.')
  end

  def finish
    state_change({direct_contact: :update, application: :update}, ->{@job.offered? || @job.running?}, ->{@job.finish!}, :finished, 'The job is now finished.', 'The job could not be finished.')
  end

  private

  def job_offered_lambda
    ->{@job.offered?}
  end

  def create_job_or_message(job_offered, job_message, failure_template)
    if @job.save
      UserMailer.message_sent(@job.other_user(current_user), @job, job_message, current_user, job_offered).deliver
      flash[:notice] = job_offered ? 'The job has been offered.' : 'Your message has been sent.'
      redirect_to edit_job_path(@job)
    else
      flash[:alert] = job_offered ? 'The job could not be offered.' : 'Your message could not be sent.'
      render failure_template
    end
  end

  def required_account_is_conditional
    @job = Job.find(params[:id])
    if action_name == 'offer' || action_name == 'cancel'
      @job.kind_of?(JobFromDirectContact) ? client_required : programmer_required
    elsif action_name == 'start' || action_name == 'decline'
      @job.kind_of?(JobFromDirectContact) ? programmer_required : client_required
    end
  end

  def offer_job_with_message(job)
    if params[:'offer-contract'].present? && job.has_not_started? && (job.is_client?(current_user) != job.kind_of?(JobFromApplication))
      job.state = 'offered'
      job.started_at = Time.now
      return true
    end
    false
  end

  def state_change(permission_required_hash, state_required, action, action_name, success_message, failure_message)
    @job = Job.find(params[:id])
    permission_required = @job.kind_of?(JobFromApplication) ? permission_required_hash[:application] : permission_required_hash[:direct_contact]
    authorize! permission_required, @job
    if state_required.call
      action.call
      UserMailer.state_occurred_to_job(@job.other_user(current_user), @job, current_user, action_name).deliver
      flash[:notice] = success_message
    else
      flash[:alert] = failure_message
    end
    redirect_to action: :edit
  end

  def redirect_to_existing_job(programmer, client)
    existing_jobs = Job.where('programmer_id = ? AND client_id = ? AND (state = ? OR state = ? OR state = ?)', programmer.id, client.id, 'has_not_started', 'offered', 'running')
    redirect_to edit_job_path(existing_jobs.first) unless existing_jobs.empty?
  end

  def create_job_params
    params.require(:job).permit(:programmer_id, :name, job_messages_attributes: [:content])
  end

  def create_job_application_params
    params.require(:job).permit(:job_listing_id, :rate_type, :hourly_rate, :fixed_rate, job_messages_attributes: [:content])
  end

  def create_message_params
    params.require(:job_message).permit(:content)
  end

end

app/views/jobs/_job_info.slim
- is_client = @job.is_client?(current_user)
- is_job_application = @job_listing.present? || @job.kind_of?(JobFromApplication)
- is_initiator = (is_client && !is_job_application) || (!is_client && is_job_application)
.span4
  p
    - if is_client
      strong
        = link_to @programmer.user.full_name, programmer_path(@programmer), target: '_blank'
    - else
      strong
        = @job.client.user.full_name
      br
      = @job.client.company
  p
    - unless is_job_application
      - rate_text_object = @job.has_not_started? ? @programmer : @job
      - if is_client
        = client_rate_text(rate_text_object)
      - else
        = programmer_rate_text(rate_text_object)

  - unless @job.new_record?
    - if @job.has_not_started?
      - if is_initiator
        p
          = link_to 'Offer Contract', offer_job_path(@job), class: 'btn btn-success', method: :post
      - else
        | Job has not been offered yet
    - elsif @job.offered?
      - if is_initiator
        p
          = link_to 'Cancel Contract', cancel_job_path(@job), class: 'btn btn-danger', method: :post
      - else
        p
          = link_to 'Start Job', start_job_path(@job), class: 'btn btn-success', method: :post
        p
          = link_to 'Decline Job', decline_job_path(@job), class: 'btn btn-danger', method: :post
      | Job Offered

    - elsif @job.running?
      p
        = link_to 'Finish Job', finish_job_path(@job), class: 'btn btn-success', method: :post
      | Job Running

    - elsif @job.finished?
      | Job Finished
    - elsif @job.disabled?
      | Job Disabled

app/views/jobs/edit.slim
= form_for [@job], url: {action: :create_message}, html: {class: 'form-horizontal'}, method: :post do |f|
  .span8
    .offset1.span6
      - @job.job_messages.each do |message|
        - if message.valid?
          p
            .pull-right
              = message.created_at_text
            strong
              = message.sender_name
            br
            = simple_format(message.content)
    .offset1.span6
      p
        = text_area_tag 'job_message[content]', @job_message.present? ? @job_message.content : '', class: 'span6 longer-text'
    .offset1.span6
      - if @job.has_not_started?
        .pull-right
          = f.submit 'Send and Offer Contract', class: 'btn btn-success', name: 'offer-contract', data: {disable_with: 'Submitting...'}
      p
        = f.submit 'Send Message', class: 'btn', data: {disable_with: 'Submitting...'}

  = render partial: 'jobs/job_info'

app/views/jobs/index.slim
- unless @jobs_as_client.empty?
  h3
    | Jobs as Client
  - @jobs_as_client.each do |job|
    p
      strong
        = link_to job.name, edit_job_path(job)
        |&nbsp;-&nbsp;
        = job.programmer.user.full_name
        |&nbsp;-&nbsp;
      = job.state.humanize

- unless @job_listings_as_client.empty?
  h3
    | Job Listings as Client
  - @job_listings_as_client.each do |job_listing|
    p
      = link_to "#{job_listing.title}#{job_listing.ended ? ' (ended)' : ''}", edit_job_listing_path(job_listing)

- unless @jobs_as_programmer.empty?
  h3
    | Jobs as Programmer
  - @jobs_as_programmer.each do |job|
    p
      strong
        = link_to job.name, edit_job_path(job)
        |&nbsp;-&nbsp;
        = job.client.user.full_name
        |&nbsp;-&nbsp;
      = job.state.humanize

- if @jobs_as_client.empty? && @job_listings_as_client.empty? && @jobs_as_programmer.empty?
  | You currently have no jobs set up.

app/views/jobs/new.slim
= form_for [@job], url: {action: :create}, html: {class: 'form-horizontal'} do |f|
  .span8
    = f.hidden_field :programmer_id, value: @programmer.id
    .control-group class="#{model_attribute_class(@job, :name)}"
      .control-label
        = f.label :name, 'Job Name'
      .controls
        = f.text_field :name, placeholder: 'Job Name'
        = render partial: 'shared/help_inline', locals: {model: @job, attribute: :name}
    .control-group
      .control-label
        | Message
      .controls
        = text_area_tag 'job[job_messages_attributes][][content]', @job.job_messages.first.present? ? @job.job_messages.first.content : '', class: 'span5 longer-text'
    .offset2.span5
      .pull-right
        = f.submit 'Send and Offer Contract', class: 'btn btn-success', name: 'offer-contract', data: {disable_with: 'Submitting...'}
      p
        = f.submit 'Send Message', class: 'btn', data: {disable_with: 'Submitting...'}
  = render partial: 'jobs/job_info'

app/views/jobs/new_application.slim
= form_for [@job], url: {action: :create_application}, html: {class: 'form-horizontal'} do |f|
  .span8
    = f.hidden_field :job_listing_id, value: @job_listing.id
    .control-group
      .control-label
      .controls
        = @job_listing.title
    .control-group
      .control-label
        | Message
      .controls
        = text_area_tag 'job[job_messages_attributes][][content]', @job.job_messages.first.present? ? @job.job_messages.first.content : '', class: 'span5 longer-text'
    .control-group
      .control-label
        | Rate Type
      .controls
        label class='radio'
          = f.radio_button :rate_type, :hourly
          | Hourly or daily rate
        label class='radio'
          = f.radio_button :rate_type, :fixed_price
          | Fixed price for project

    span id='hourly_rate_fields' class="#{@job.hourly? ? '' : 'hidden'}"
      .control-group class="#{model_attribute_class(@job, :hourly_rate)}"
        .control-label
          = f.label :hourly_rate, 'Rate Per Hour'
        .controls
          ' $
          = f.text_field :hourly_rate, class: 'short-field'
          = render partial: 'shared/help_inline', locals: {model: @job, attribute: :hourly_rate}

    span id='fixed_rate_fields' class="#{@job.fixed_price? ? '' : 'hidden'}"
      .control-group class="#{model_attribute_class(@job, :fixed_rate)}"
        .control-label
          = f.label :fixed_rate, 'Rate For Project'
        .controls
          ' $
          = f.text_field :fixed_rate, class: 'short-field'
          = render partial: 'shared/help_inline', locals: {model: @job, attribute: :fixed_rate}

    javascript:
      $('document').ready(function() {
        var refreshFields = function() {
          current_rate_type = $("input[name='job[rate_type]']:checked").val();
          if (current_rate_type == 'hourly') {
            $('#hourly_rate_fields').show();
            $('#fixed_rate_fields').hide();
          } else if (current_rate_type == 'fixed_price') {
            $('#hourly_rate_fields').hide();
            $('#fixed_rate_fields').show();
          } else {
            $('#hourly_rate_fields').hide();
            $('#fixed_rate_fields').hide();
          }
        };

        $('#job_rate_type_hourly').on('click', refreshFields);
        $('#job_rate_type_fixed_price').on('click', refreshFields);
        refreshFields();
      });

    .offset2.span5
      .pull-right
        = f.submit 'Send and Offer Bid', class: 'btn btn-success', name: 'offer-contract', data: {disable_with: 'Submitting...'}
      p
        = f.submit 'Send Message', class: 'btn', data: {disable_with: 'Submitting...'}
  = render partial: 'jobs/job_info'