config/routes.rb
Codedoor::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'application#main'

  resources :programmers, only: [:index, :show]

  resources :jobs, only: [:index, :new, :create, :edit] do
    get :new_application, on: :new
    post :create_application, on: :new

    post :create_message, on: :member
    post :cancel, on: :member
    post :offer, on: :member
    post :decline, on: :member
    post :start, on: :member
    post :finish, on: :member
  end

  resources :job_listings, only: [:index, :show, :new, :edit, :create, :update]

  resources :users, only: [:edit, :update] do
    resource :programmer, only: [:edit, :update] do
      post :verify_contribution, defaults: { format: :json }
    end
    resource :client, only: [:new, :create, :edit, :update]
    # resource :payment_info, only: [:edit] do
    #   # The Balanced Payments API scrubs the _method parameter, so :update must be a POST
    #   post :update, defaults: { format: :json }
    # end
  end

  resources :blog, only: [:index, :show]

  get '/terms', to: 'legal#terms'
  get '/sitemap.xml.gz', to: 'sitemaps#show'
  get '/login', to: 'login#main'

end

app/views/shared/_alert_message.slim
p class='alert alert-error flash-message'
  button type='button' class='close' data-dismiss='alert'
    | &times;
  = message

app/views/shared/_back_to_search.slim
a id="back-to-search"
  | Back to search
javascript:
  $('#back-to-search').on('click', function(){ history.back(); });

app/views/shared/_error_messages.slim
p class='alert alert-error flash-message'
  button type='button' class='close' data-dismiss='alert'
    | &times;
  | Errors have occurred when trying to process the action.
  br
  br
  - messages.each do |error_message|
    = error_message
    br

app/views/shared/_flash_messages.slim
/ Flash lasts for one page view for the purpose of redirects.
/ Clear the flash to ensure that the message doesn't stay
/ for another page load when there is no redirect.
- if flash[:alert]
  = render partial: 'shared/alert_message', locals: {message: flash[:alert]}
  - flash[:alert] = nil
- if flash[:notice]
  = render partial: 'shared/notice_message', locals: {message: flash[:notice]}
  - flash[:notice] = nil
- if flash[:errors]
  = render partial: 'shared/error_messages', locals: {messages: flash[:errors]}
  - flash[:errors] = nil

app/views/shared/_help_block.slim
- if model_has_error?(model, attribute)
  span.help-block
    = model_error_message(model, attribute)

app/views/shared/_help_inline.slim
- if model_has_error?(model, attribute)
  span.help-inline
    = model_error_message(model, attribute)

app/views/shared/_navbar.slim
div class="navbar"
  div class="navbar-inner"
    strong
      a class="pull-left" href="#{root_path}"
        | CodeDoor
    - if user_signed_in?
      a class="pull-right" href="#{destroy_user_session_path}" data-method="delete"
        | Log out
      - if current_user.completed_programmer_account?
        a class="pull-left" href="#{programmer_path(current_user.programmer)}"
          | Profile
      - if current_user.client.present?
        a class="pull-left" href="#{programmers_path}"
          | Search
      - if current_user.completed_programmer_account? || current_user.client.present?
        a class="pull-left" href="#{jobs_path}"
          | Jobs
      / Only show if if user is client and not programmer
      - unless current_user.client.present? && !current_user.completed_programmer_account?
        a class="pull-left" href="#{job_listings_path}"
          | Find Work
      - if current_user.client.present?
        a class="pull-left" href="#{new_job_listing_path}"
          | Create Job Listing
      a class="pull-right" href="#{edit_user_path(current_user)}"
        | Settings
    - else
      a class="pull-left" href="#{job_listings_path}"
        | Find Work
      a class="btn-auth btn-github pull-right" href="#{user_omniauth_authorize_path(:github)}"
        | Log in with GitHub
      a class="pull-right" href="#{new_user_session_path}"
        | Log in
      a class="pull-right" href="#{new_user_registration_path}"
        | Sign up

app/views/shared/_notice_message.slim
p class='alert flash-message'
  button type="button" class="close" data-dismiss="alert"
    | &times;
  = message

app/views/shared/_rate_badge.slim
.rate-badge.pull-right
  = client_rate_text(programmer)
  - if !programmer.unavailable?
    br
    small
      .rate-badge-availability.pull-right
        = programmer.calculated_availability.to_s.humanize

app/views/shared/_search_form.slim
= form_tag(programmers_path, method: :get)
  small
    | Skills
  br
  select id='skill_name' name='skill_name'
    = options_for_select(Skill.all.map{|skill| [skill.name, skill.name]}.insert(0, 'Select Skill:'), @programmer_search.skill_name)
  br
  small
    | Availability
  br
  label class='radio'
    = radio_button_tag('availability', '', !@programmer_search.availability_chosen?)
    | Any
  label class='radio'
    = radio_button_tag('availability', 'full-time', @programmer_search.availability == 'full-time')
    | Full-time
  label class='radio'
    = radio_button_tag('availability', 'part-time', @programmer_search.availability == 'part-time')
    | Part-time
  small
    | Hourly Rate
  br
  .rate-range
    | $
    = text_field_tag 'min_rate', @programmer_search.min_rate, class: 'rate-field'
    | &nbsp;to&nbsp;
    = text_field_tag 'max_rate', @programmer_search.max_rate, class: 'rate-field'
    | (USD)
  br
  label class='checkbox'
    = check_box_tag 'contract_to_hire', true, @programmer_search.contract_to_hire
    | Will consider contract to hire
  = submit_tag 'Search', class: 'btn btn-search'

  br
  br
  ' Or Create A
  a href="#{new_job_listing_path}" target="_blank"
    | Job Listing