config/routes.rb
Codedoor::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'application#main'

  resources :programmers, only: [:index, :show]

  resources :jobs, only: [:index, :new, :create, :edit] do
    get :new_application, on: :new
    post :create_application, on: :new

    post :create_message, on: :member
    post :cancel, on: :member
    post :offer, on: :member
    post :decline, on: :member
    post :start, on: :member
    post :finish, on: :member
  end

  resources :job_listings, only: [:index, :show, :new, :edit, :create, :update]

  resources :users, only: [:edit, :update] do
    resource :programmer, only: [:edit, :update] do
      post :verify_contribution, defaults: { format: :json }
    end
    resource :client, only: [:new, :create, :edit, :update]
    # resource :payment_info, only: [:edit] do
    #   # The Balanced Payments API scrubs the _method parameter, so :update must be a POST
    #   post :update, defaults: { format: :json }
    # end
  end

  resources :blog, only: [:index, :show]

  get '/terms', to: 'legal#terms'
  get '/sitemap.xml.gz', to: 'sitemaps#show'
  get '/login', to: 'login#main'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include RequireAccountRedirect

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  check_authorization
  skip_authorization_check

  # TODO: remove hack to make CanCan work with Rails 4
  before_filter do
    resource = controller_path.singularize.gsub('/', '_').to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_cannot_be_found
  end

  rescue_from ActiveRecord::RecordNotFound do |exception|
    redirect_cannot_be_found
  end

  def main
    @custom_description = 'CodeDoor is a marketplace for freelance programmers that have contributed to open source software.'
    render('loggedout') unless current_user.present?
  end

  def after_sign_in_path_for(resource)
    if cookies[:after_client_signed_up_path].present?
      next_path_for_account(:client) || path_from_cookie(:after_client_signed_up_path)
    elsif cookies[:after_programmer_signed_up_path].present?
      next_path_for_account(:programmer) || path_from_cookie(:after_programmer_signed_up_path)
    else
      next_path_for_account(:client_or_programmer) || path_from_cookie(:after_account_signed_up_path) || root_path
    end
  end

  protected

  def redirect_cannot_be_found
    redirect_to root_url, alert: 'Information cannot be found.'
  end

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super # Use the default one
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def model_has_error?(model, attribute)
    model.errors.has_key?(attribute)
  end

  def model_attribute_class(model, attribute)
    model_has_error?(model, attribute) ? 'error' : ''
  end

  def model_attribute_class_array(model, attribute_array)
    attribute_array.each do |attribute|
      return 'error' if model_has_error?(model, attribute)
    end
    ''
  end

  def model_error_message(model, attribute)
    return '' unless model_has_error?(model, attribute)
    messages = model.errors.messages[attribute]
    messages.empty? ? '' : "#{attribute.to_s.humanize} #{messages.to_sentence}."
  end

  def repo_commits_link(username, repo_owner, repo_name, text)
    link_to(text, GithubRepo.repo_commits_url(username, repo_owner, repo_name), target: '_blank')
  end

  # The rate object can be a programmer or job
  def client_rate_text(rate_object)
    rate_text(rate_object, false)
  end

  def programmer_rate_text(rate_object)
    rate_text(rate_object, true)
  end

  private

  def rate_text(rate_object, viewing_as_programmer)
    case rate_object.availability
    when 'part-time'
      rate = viewing_as_programmer ? rate_object.hourly_rate : rate_object.hourly_rate_to_client
      render_rate_text(rate, 'hour')
    when 'full-time'
      rate = viewing_as_programmer ? rate_object.daily_rate_to_programmer : rate_object.daily_rate_to_client
      render_rate_text(rate, 'day')
    else
      'Unavailable'
    end
  end

  def render_rate_text(rate, time_period)
    # If the rate happens to be a certain number of dollars, do not include cents.  Otherwise, include cents.
    "#{number_to_currency(rate, precision: rate.to_i.to_f == rate ? 0 : 2)} / #{time_period}"
  end
end

app/views/application/loggedout.slim
.splashlogo
  = image_tag('logo.png')

.row
  .introbox_container
    span class="introbox pull-right"
      h2
        | Programmers
      p
        | Work for clients who recognize top open source contributors.
      p
        | Bill by the day.
      a class="btn-auth btn-github" href="#{user_omniauth_authorize_path(:github)}"
        | Sign up with GitHub
    span class="introbox pull-left"
      h2
        | Clients
      p
        | Find freelance coders who have contributed to meaningful projects.
      p
        | See their code before hiring.
      = form_tag(programmers_path, method: :get)
        select id='skill_name' name='skill_name'
          = options_for_select(Skill.all.map{|skill| [skill.name, skill.name]}.insert(0, 'Select Skill:'), params[:skill_name])
        = submit_tag 'Search', class: 'btn'
.row
  .create-job-listing
    strong
      ' Or Create A
      a href="#{new_job_listing_path}"
        | Job Listing

.row
  .intro-explanation-header
    h3
      | How It Works
.row
  .span4
    .intro-workflow-img
      = image_tag('profile.png')
  .span4
    .intro-workflow-img
      = image_tag('list.png')
  .span4
    .intro-workflow-img
      = image_tag('exchange.png')

.row
  .span4
    .intro-workflow-desc
      | Talented coders build a portfolio, connecting their code on GitHub
  .span4
    .intro-workflow-desc
      | Savvy clients search for coders with the skills for their projects
  .span4
    .intro-workflow-desc
      | Clients get high quality work, coders get high quality pay

.row
  .intro-workflow-signup
    a class="btn-auth large btn-github" href="#{user_omniauth_authorize_path(:github)}"
      | Sign up with GitHub
    br
    a href="#{new_user_registration_path}"
      | Or sign up via email (for clients)

app/views/application/main.slim
p
  = current_user.full_name
p
  = link_to('Search programmers', programmers_path)
p
  = link_to('Edit user account', edit_user_path(current_user))
  - if current_user.checked_terms?
    - if current_user.completed_programmer_account?
      p
        = link_to('View your information', programmer_path(current_user.programmer))
    - else
      p
        = link_to('Create programmer account', edit_user_programmer_path(current_user))

    - unless current_user.client.present?
      p
        = link_to('Create client account', new_user_client_path(current_user))